### ISSUE TITLE
Generic Callback

### ISSUE THREAD

**Issue by RAMAMario** [faaxm/spix#11]
Hi,

I have the use-case where the application under test shall be fed by the external test script using the AnyRPC with some initial backend state.
So I quickly cooked up a generic callback implementation where one can send arbitrary data to the application under test.

So basically, the application under test would define a callback like so:
```
server.setGenericCommandHandler([](std::string command, std::string payload) {
   // do whatever needs to be done
});
```

and the script would feed in my case the initial state to the application before doing the usual stuff:
```
s = xmlrpc.client.ServerProxy('http://localhost:9000')
s.command('loadBackendState', 'BackendData')
```

Would this generally be a feature of interest?

**Comment by faaxm** [comment]
Hi @RAMAMario!
Sorry it took me a while to get back to you about this! Generally I think this is a cool idea, I am only wondering if there is a more generic way of expressing the `payload`, i.e. not forcing it to be a string. Admittedly this is the same thing that Spix already does with how it currently converts values to strings... So, I'd say it's good enough for now but once I find time to make the value-handling of Spix more generic, I might take the liberty of breaking the API you introduced ;-)

I am a bit busy right now and might take some time, but if you have something ready, please feel free to open a PR :-)
