### ISSUE TITLE
Consider renaming the project

### ISSUE THREAD

**Issue by BrendanL79** [faaxm/spix#118]
The project name's similarity to a common racial slur, while likely unintended, makes it difficult to discuss the project in a professional setting. This could be a limiting factor in its future growth and success.

**Comment by faaxm** [comment]
This library is named after the _Spix's Macaw_, the bird that also serves as mascot and part of the logo.

**Comment by BrendanL79** [comment]
I know that, and you know that, but the fact remains that it's a homonym of a racial slur. It's a problem, same way no one with any sense uses the adverb "niggardly" anymore.
