### ISSUE TITLE
Compile error Ubuntu 18.04

### ISSUE THREAD

**Issue by eelcoverschoor** [faaxm/spix#15]
Code will not compile on Ubuntu 18.04 due to missing `#include <atomic> `  in AnyRpcServer.cpp. Adding the include solves this

- updated comment

**Comment by faaxm** [comment]
Thanks for reporting this, could you let me know which header you had to add?

**Comment by eelcoverschoor** [comment]
Sorry forgot to mention it. I included <atomic>
