### ISSUE TITLE
Cmake not working anymore on Linux

### ISSUE THREAD

**Issue by ythoma** [faaxm/spix#23]
Hi,
Thanks for your very good library. The last commits (cmake-cleanup) did break something.
On an Ubuntu 18.04, ti works well with commit 071eebaa8fa6c0a480bab7f74d0e95ccdc1b0102, but not with the last one (00cf734165a43e283408f97e93004bb2a61d5c34 )

I got this message during "cmake ..":

CMake Error at CMakeLists.txt:39 (install):
  install TARGETS given target "Spix" which does not exist in this directory.

-- Configuring incomplete, errors occurred!

Thanks for your nice job :-)

**Comment by anszom** [comment]
Just encountered the same problem. It seems that with CMake older than 3.13, install(TARGETS Spix ...) must be in the same directory as add_library(Spix ...). Simply moving the offending install() directive to the lib/CMakeLists.txt seems to work.

See https://stackoverflow.com/questions/34443128/cmake-install-targets-in-subdirectories

**Comment by faaxm** [comment]
Thanks for the feedback, I will look into this later today and probably move the `install` part back into `lib`...

**Comment by ythoma** [comment]
I forgot to mention I have cmake version  3.10.2. It is coherent with what @anszom noticed.

**Comment by faaxm** [comment]
@ythoma @anszom I don't have an older version of cmake at hand, but I think the linked PR #24 should fix the issue. Maybe you could checkout the branch and give it a try?

**Comment by anszom** [comment]
Now it builds & installs without errors. Thanks.

**Comment by ythoma** [comment]
I confirm, it builds and installs without errors. Thanks for your quick modifs.
