### ISSUE TITLE
Get items by id

### ISSUE THREAD

**Issue by m-kuhn** [faaxm/spix#33]
Thank you for this very nice library, I am just testing it for https://github.com/opengisch/QField/

One place where I could see some potential for improvement is by allowing to use `id`'s instead of `objectName`'s, plenty of the code already defines ids, but almost nowhere objectNames, so the overhead for writing tests could be lowered.

What I think would need to be done:

 - Think about a syntax for the path
 - Pass the QmlEngine into spix, to do something like here https://stackoverflow.com/a/43274356/2319028

Happy to hear back any feedback on this.

**Comment by krussjos** [comment]
See here:

https://github.com/faaxm/spix/pull/34
