### ISSUE TITLE
getStringProperty with compound properties

### ISSUE THREAD

**Issue by RAMAMario** [faaxm/spix#60]
Given the following element:
`
Text  {
    text: "Hello World!"
    objectName: "test"
    font.family: "Helvetica"
    font.pointSize: 24
}
`

How would one proceed to query the font family with getStringProperty(...)?

I tried the following approaches and none seems to return anything:

getStringProperty("test", "font.family")

getStringProperty("test/font", "family")

Am I doing something wrong or is there an issue?

**Comment by faaxm** [comment]
The `font.family` is just a convenience way of accessing the font-family in qml. Internally the object only has a `font` property and spix does not support accessing "properties of properties". Instead, you could access the whole font via `getStringProperty("test", "font")` which will then be converted to a string looking something like `Helvetica,24,-1,5,50,0,0,0,0,0`

If you want to further experiment with this, you can add a call to `utils::DumpObject(m_item);` in `QtItem::stringProperty` which will dump all available properties of an item to the console. You will also have to uncomment some code in `utils/DebugDump.cpp` first.

I am not sure if there is a good way to extend Spix to handle these "sub-properties". `font` is an object of type `QFont` and it does not actually export the family as a property, but only provides accessor methods in c++. At least from what I could see when I had a quick look. One could make Spix smarter to understand common objects, but I am not sure if this would end up as  a big mess once more and more types are added. :-/

**Comment by RAMAMario** [comment]
Ok understood. Not really a big problem I would say, so closing for now.

Thanks for the fast reply.
