### ISSUE TITLE
Create 0.6 release

### ISSUE THREAD

**Issue by ddillon89** [faaxm/spix#93]
Hello,

I have currently https://github.com/faaxm/spix/issues/87 which has been fix by this merge https://github.com/faaxm/spix/pull/91.
I need to get spix from conan which don't have this fix,
Is there a possibility to tag the main branch with a new version like 0.6 or 0.51 ?
Next, I'm in contact with @fdgStilla to add the new spix receipe in [conan-center](https://github.com/conan-io/conan-center-index/tree/master/recipes/spix)

Thanks for your work and your help

**Comment by faaxm** [comment]
Done. 🙂  And thanks for taking care of the conan receipe!

Also tagging @Neumann-A as this might be relevant for vcpkg.
